dependencies:
 - smartcontractkit/chainlink-brownie-contracts@1.2.0
 - OpenZeppelin/openzeppelin-contracts@3.1.0
compiler:
    solc:
        remappings:
         - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0"
networks:
    default: development # the default network that brownie connects to
    development:
        cmd_settings:
            accounts: 20


